apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: postgresql-hooks
actions:
  backupPrehook:
    phases:
    - func: KubeExec
      name: makePGCheckPoint
      args:
        namespace: "{{ .StatefulSet.Namespace }}"
        pod: "{{ index .StatefulSet.Pods 0 }}"
        container: postgresql
        command:
        - bash
        - -o
        - errexit
        - -o
        - nounset
        - -o
        - pipefail
        - -c
        - |
          PGPASSWORD=${POSTGRES_PASSWORD} psql -U postgres -c "select pg_start_backup('app_cons');"
  backupPosthook:
    phases:
    - func: KubeExec
      name: afterPGBackup
      args:
        namespace: "{{ .StatefulSet.Namespace }}"
        pod: "{{ index .StatefulSet.Pods 0 }}"
        container: postgresql
        command:
        - bash
        - -o
        - errexit
        - -o
        - nounset
        - -o
        - pipefail
        - -c
        - |
          PGPASSWORD=${POSTGRES_PASSWORD} psql -U postgres -c "select pg_stop_backup();"
